packages:
  # Spotify Player
  - id: spotify-player
    winget-id: aome510.spotify-player  #
    version-source:
      type: github
      owner: aome510
      repo: spotify-player
    version-parser:
      type: regex
      pattern: ^v(\d+\.\d+\.\d+)$
      tag-filter: ^v\d+\.\d+\.\d+$
    installers:
      - architecture: x64
        url: https://github.com/aome510/spotify-player/releases/download/v{version}/spotify_player-x86_64-pc-windows-msvc.zip
        installer-type: zip
    skip-checks: []

  # uv (Astral)
  - id: uv
    winget-id: astral-sh.uv
    version-source:
      type: github
      owner: astral-sh
      repo: uv
    version-parser:
      type: regex
      pattern: ^(\d+\.\d+\.\d+)$
      tag-filter: ^\d+\.\d+\.\d+$
    installers:
      - architecture: x64
        url: https://github.com/astral-sh/uv/releases/download/{version}/uv-x86_64-pc-windows-msvc.zip
        installer-type: zip
    skip-checks: []

  - id: just
    winget-id: casey.just
    version-source:
      type: github
      owner: casey
      repo: just
    version-parser:
      type: regex
      pattern: ^(\d+\.\d+\.\d+)$
      tag-filter: ^\d+\.\d+\.\d+$
    installers:
      - architecture: x64
        url: https://github.com/casey/just/releases/download/{version}/just-{version}-x86_64-pc-windows-msvc.zip
        installer-type: zip
    skip-checks: []
